library(tidyverse)
library(caret)
library(readxl)
library(fpc)
library(factoextra)
library(ggthemes)
library(gridExtra)
library(plotly)


# General
## % of number and amount of donations per cluster
dataset_donations %>% 
  mutate(
    total.amount.donations = sum(donation.amount),
    total.count.donations = n()
  ) %>%  
  group_by(cluster.assigned) %>% 
  mutate(
    perc.count.donations.total = (n() / total.count.donations)* 100,
    perc.sum.amount.donations.total = (sum(donation.amount) / total.amount.donations)*100
  )%>% 
  ungroup() %>% 
  distinct(cluster.assigned, .keep_all = TRUE) %>% 
  select(cluster.assigned, "% Number Donations" = perc.count.donations.total, 
         "% Amount of donations (GBP)" = perc.sum.amount.donations.total, 
         -c(total.amount.donations, total.count.donations)) %>%  
  mutate_at(vars(cluster.assigned), funs(as.factor)) %>% 
  gather(index, value, - cluster.assigned) %>% 
  ggplot(aes(cluster.assigned, value, fill = cluster.assigned)) +
  geom_col(alpha = 0.8) +
  facet_grid(. ~ index) +
  labs(title = "Number and Amount of Donations by Cluster", 
       x = "", 
       y = "Value (%)") +
  theme_economist() + 
  scale_fill_economist() + 
  theme(legend.position = "right", 
        plot.title = element_text(size=20), 
        plot.subtitle = element_text(size = 12), 
        text = element_text(family = "Tahoma"),
        panel.background = element_rect(fill = "#cee0e6")) + 
  guides(fill=guide_legend(title= "Cluster Assigned"))

# Number donors
## Percentage of donors  
plotPercDonorsClus1 <- dataset_viz_clustering_unique_donors %>% 
  filter(
    index == "perc.count.donors.group"
  ) %>% 
  ggplot(aes(donor.category, value)) +
  geom_col() +
  facet_grid(. ~ cluster.assigned) +
  labs(
    title = "What % of of each category's number of donors are on every cluster?", 
    x = "", 
    y = "% Donors of category"
  ) +
  theme_economist() + 
  scale_color_economist() + 
  theme(legend.position = "right", 
        plot.title = element_text(size=13), 
        plot.subtitle = element_text(size = 12), 
        text = element_text(family = "Tahoma"),
        axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))  

grid.arrange(plotPercDonorsClus1, plotAllClusters, nrow=1, ncol=2)

# Comment: DONE



# Amount donations
## Percentage of group amount donations  
plotPercDonClus1 <- dataset_viz_clustering %>% 
  filter(
    index == "perc.sum.amount.donations.group"
  ) %>% 
  ggplot(aes(donor.category, value)) +
  geom_col() +
  facet_grid(. ~ cluster.assigned) +
  labs(
    title = "What % of of each category's donations are on every cluster?", 
    x = "", 
    y = "% Amount Donations of category"
  ) +
  theme_economist() + 
  scale_color_economist() + 
  theme(legend.position = "right", 
        plot.title = element_text(size=15), 
        plot.subtitle = element_text(size = 12), 
        text = element_text(family = "Tahoma"),
        axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) + 
  guides(color=guide_legend(title= "Titulo leyenda"))

grid.arrange(plotPercDonClus1, plotAllClusters, nrow=1, ncol=2)

# Comment: cluster 2 contains the majority income generated by every donor category
# We see Outliers cluster containing a relevant part of Public Sector, Trusts, Legator



## Percentage of total amount donations  
plotPercTotalDonClus1 <- dataset_viz_clustering %>% 
  filter(
    index == "perc.sum.amount.donations.total"
  ) %>% 
  ggplot(aes(donor.category, value)) +
  geom_col() +
  facet_grid(. ~ cluster.assigned) +
  labs(
    title = "What % of global donations are on every cluster and category?", 
    x = "", 
    y = "% Amount Donations"
  ) +
  theme_economist() + 
  scale_color_economist() + 
  theme(legend.position = "right", 
        plot.title = element_text(size=15), 
        plot.subtitle = element_text(size = 12), 
        text = element_text(family = "Tahoma"),
        axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) + 
  guides(color=guide_legend(title= "Titulo leyenda"))

grid.arrange(plotPercTotalDonClus1, plotAllClusters, nrow=1, ncol=2)

# Comment: Apart from the general public, we see the Corporate donors
# delivering a high portion of global Hospice's donations. mostly being
# inside the outlier cluster
# General public is mostly in second cluster, and some in 1


# Income per cluster
# Count Donors

plotDevIncomePercDonors <- dataset_donations %>% 
  distinct(donor.no, .keep_all = TRUE) %>% 
  mutate(
    total.count.donors = n()
  ) %>%  
  group_by(development.income, cluster.assigned) %>% 
  mutate(
    perc.count.donors = (n() / total.count.donors)* 100
  )%>% 
  distinct(development.income, .keep_all = TRUE) %>%
  ungroup() %>% 
  select(development.income, cluster.assigned, perc.count.donors) %>% 
  gather(index, value, -development.income, -cluster.assigned) %>% 
  ggplot(aes(development.income, value)) +
  geom_col(alpha = 0.8) +
  facet_grid(. ~ cluster.assigned) +
  labs(title = "What % of donors are on every cluster?", 
       x = "", 
       y = "Percentage Donors (%)") +
  theme_economist() + 
  scale_fill_economist() + 
  theme(legend.position = "right", 
        plot.title = element_text(size=13), 
        plot.subtitle = element_text(size = 12), 
        text = element_text(family = "Tahoma"),
        axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) + 
  guides(fill=guide_legend(title= "Cluster Assigned"))


# Sum donations
plotDevIncomePercAmountDon <- dataset_donations %>% 
  mutate(total.count.donations = n(),
         total.amount.donations = sum(donation.amount)) %>% 
  group_by(development.income, cluster.assigned) %>% 
  mutate(perc.count.development.income = (n() / total.count.donations)*100,
         perc.amount.donations.development.income = (sum(donation.amount) / total.amount.donations)*100
  ) %>% 
  # ungroup() %>% 
  distinct(development.income, .keep_all = TRUE) %>%
  ungroup() %>% 
  select(development.income, cluster.assigned, perc.amount.donations.development.income) %>% 
  gather(index, value, -development.income, -cluster.assigned) %>% 
  filter(index == "perc.amount.donations.development.income") %>% 
  ggplot(aes(development.income, value)) +
  geom_col(alpha = 0.8) +
  facet_grid(. ~ cluster.assigned) +
  labs(
    title = "What % of total amount of donations are on every cluster?", 
    x = "", 
    y = "% Amount of donations"
  ) +
  theme_economist() + 
  scale_color_economist() + 
  theme(legend.position = "right", 
        plot.title = element_text(size=13), 
        plot.subtitle = element_text(size = 12), 
        text = element_text(family = "Tahoma"),
        axis.text.x=element_text(angle=90,hjust=1,vjust=0.5, size=8))


grid.arrange(plotDevIncomePercDonors, plotDevIncomePercAmountDon, nrow=1, ncol=2)


# Comment: in terms of number of donors the cluster 2 takes the lead
# containing mainly Individuals, Events, and Community 
#   but when we meassure the income they generate it's value reduces almost
#   4 times


