---
title: "Donations Dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme: flatly
    orientation: columns
    vertical_layout: fill
runtime: shiny
runApp: showcase
---


```{r global, include = FALSE}


library(tidyverse)
library(readxl)
library(ggthemes)
# library(astsa)
# library(forecast)
# library(xts)
# library(aspace)
# library(forecast)
# library(data.table)
library(leaflet)
library(plotly)


########################  Import data ########################

# Donations dataset

### Group codes
## Import table with group codes
table_group_codes <-
  read_excel(
    "~/Google Drive/Data Analysis/Bases de Datos/St. Cuthberts/Support Services/nominal ledgers and source groups.xlsx"
  ) %>%
  select(-Recnum) %>%
  rename_all(funs(tolower(make.names(.)))) %>%
  rename_all(funs(gsub("_", ".", .)))


### Source codes, group codes
## Import table with sources codes and join with group codes
table_source_codes <-
  read_excel(
    "~/Google Drive/Data Analysis/Bases de Datos/St. Cuthberts/Support Services/all source codes.xlsx",
    skip = 1
  ) %>%
  rename_all(funs(tolower(make.names(.)))) %>%
  rename_all(funs(gsub("_", ".", .))) %>%
  select(-c(not.in.use)) %>%
  mutate(source.group = substr(source, 1, 3)) %>%
  rename_all(funs(tolower(make.names(.)))) %>%
  rename_all(funs(gsub("_", ".", .))) %>%
  left_join(table_group_codes, by = "source.group") %>%
  mutate_if(is.character, funs(as.factor))


### Source codes, group codes, nominal descriptions
## Import table with nominal descriptions and join with source/group codes
table_nominal_descriptions <-
  read_excel(
    "~/Google Drive/Data Analysis/Bases de Datos/St. Cuthberts/Support Services/nominal descriptions.xlsx"
  ) %>%
  rename_all(funs(tolower(make.names(.)))) %>%
  mutate_all(funs(as.factor)) %>%
  left_join(table_source_codes, by = c("nominal.codes" = "nominal.ledger"))


### Income stream codes
## Import Income Stream table
table_income_stream <-
  read_excel(
    "~/Google Drive/Data Analysis/Bases de Datos/St. Cuthberts/Support Services/income stream.xlsx",
    skip = 1
  ) %>%
  rename_all(funs(tolower(make.names(.))))


### Regular donors details
## Import Regular Givers details
table_RG_details <-
  read_excel(
    "~/Google Drive/Data Analysis/Bases de Datos/St. Cuthberts/Support Services/Regular givers detail.xlsx"
  ) %>%
  rename_all(funs(tolower(make.names(.)))) %>%
  select(-c(start.date, terminated.on)) %>%
  mutate_at(vars(frequency), funs(as.factor))


### Donations
## Import main donations dataset
dataset_donations <-
      read_excel(
      "~/Google Drive/Data Analysis/Bases de Datos/St. Cuthberts/Support Services/Donations_6Years (nopass).xlsx",
      sheet = "Fernando_6year_3.7.18_1"
    ) %>%
  rename_all(funs(tolower(make.names(.)))) %>%
  select(-c(address1)) %>%
  ### Source codes, group codes, income stream, regular givers details, main dataset
  ## Join main donation dataset with Income Stream and RG
  inner_join(table_income_stream, by = "journal.no") %>%
  left_join(table_RG_details, by = c("donor.no", c("donation.amount" = "instalment.amount"))) %>%
  ### Source codes, group codes, nominal descriptions, income stream, regular givers details, main dataset
  ## Join main donations dataset with Income stream and RG with source codes, group codes, nominal descriptions
  mutate(day = strftime(.$donation.date, format = "%d")) %>%
  mutate(week = strftime(.$donation.date, format = "%V")) %>%
  mutate(month = strftime(.$donation.date, format = "%m")) %>%
  mutate(year = strftime(.$donation.date, format = "%Y")) %>%
  mutate(source.group = substr(source, 1, 3)) %>%
  left_join(table_nominal_descriptions, by = "source") %>%
  distinct(journal.no, .keep_all = TRUE) %>%
  mutate_if(is.character, funs(as.factor)) %>%
  mutate_at(vars(donor.no, nominal), funs(as.factor)) %>%
  select(
    -source.group.x,
    source.group = source.group.y,
    donor.postcode = postcode,
    donor.town = town,
    donor.gender = gender,
    donation.day = day,
    donation.week = week,
    donation.month = month,
    donation.year = year,
    everything()
  )

# IPU, CS dataset

dataset_oacc<- read_excel("~/Google Drive/Data Analysis/Bases de Datos/St. Cuthberts/Cinical Services 2015 - 13.06.2018/New Format Datasets/OACC_dataset.xlsx") %>%
  rename_all(funs(tolower(make.names(.)))) %>%
  rename_all(funs(gsub("_", ".", .))) %>%
  mutate_at(vars(q2.pain:q9.practical.matters.addressed, quality.of.life.before.admission.to.spct:lost.control), funs(as.numeric)) %>%
  mutate_if(is.character, funs(as.factor)) %>% 
  mutate_at(vars(anonymous.patient.id), funs(as.factor)) %>%
  mutate_at(vars(date.of.contact), funs(as.Date)) %>%
  group_by(date.of.contact) %>%
  mutate(mean.age = round(mean(patient.age),0)) %>%
  select(anonymous.patient.id, spell, date.of.contact) %>%
  ungroup()

### IPU
## Import IPU dataset
dataset_ipu<- read_excel("~/Google Drive/Data Analysis/Bases de Datos/St. Cuthberts/Cinical Services 2015 - 13.06.2018/New Format Datasets/IPU_dataset.xlsx") %>%
  rename_all(funs(tolower(make.names(.)))) %>%
  rename_all(funs(gsub("_", ".", .))) %>%
  mutate_if(is.character, funs(as.factor)) %>%
  mutate_at(vars(nhs.number), funs(as.factor)) %>%
  mutate_at(vars(date.of.admission..dd.mm.yyyy.), funs(as.Date)) %>% 
  select(nhs.number, spell, date.of.admission..dd.mm.yyyy., postcode)

### IPU, OACC
## Join datasets IPU and OACC
dataset_ipu_oacc<- dataset_oacc %>%
  left_join(dataset_ipu, by = c("anonymous.patient.id" =  "nhs.number", "spell"))


# Geo dataset

## Import UK postcodes table (open data)
table_postcodes <-
  read_csv(
    "~/Google Drive/Data Analysis/Bases de Datos/St. Cuthberts/Support Services/ukpostcodes.csv"
  ) %>%
  rename_all(funs(tolower(make.names(.)))) %>%
  rename_all(funs(gsub("_", ".", .))) %>%
  select(postcode, latitude, longitude)

## Join IPU, CS data with UK postcodes to get the longitud and latitude
table_CS_postcodes <-
  dataset_ipu_oacc %>%
  inner_join(table_postcodes, by = "postcode") 


# Include postcodes of donations and IPU/CS patients into main dataset
dataset_donations_postcode_ipu <- dataset_donations %>%
  left_join(table_postcodes, by = c("donor.postcode" = "postcode")) %>%
  full_join(table_CS_postcodes, by = c("donor.postcode" = "postcode")) %>%
  select(donor.no, 
         anonymous.patient.id, 
         donor.postcode, 
         latitude.x, longitude.x, 
         latitude.y, longitude.y) %>% 
  mutate_if(is.factor, funs(as.character)) %>% 
  replace_na(list(donor.no = "noMatch", anonymous.patient.id = "noMatch")) %>% 
  mutate(owner.of.postcode = case_when(donor.no == "no match" ~ "justPatient",
                                   anonymous.patient.id == "noMatch" ~ "justDonor",
                                   !anonymous.patient.id == "noMatch" ~ "bothDonorAndPatient"),
         latitude = coalesce(latitude.x, latitude.y),
         longitude = coalesce(longitude.x, longitude.y),
         copy.long = longitude,
         copy.lat = latitude) %>% 
  unite(long.lat, copy.long, copy.lat) %>% 
  distinct(long.lat, .keep_all = TRUE)  %>% 
  mutate_at(vars(owner.of.postcode), funs(as.factor)) %>% 
  select(latitude,
         longitude,
         owner.of.postcode)
  
remove(table_postcodes)


```



Donations {data-width=700}
====================

Column {data-width=300 .sidebar}
-----------------

<br>

```{r}


## Select input to select graph
selectInput(
  inputId = "graphid",
  label = "Select the Graph to Display",
  choices =  c(
    "Sum of Donations" = "sum.donations",
    "Average of Donations" = "average.donations",
    "Number of Donations" = "number.donations",
    "New Donors" = "sum.new.donors",
    "Total Donors" = "donors.per.month"
  ),
  multiple = FALSE
)

# Date input
dateRangeInput(
  inputId = "dateid1",
  label = "Select dates",
  start = "2017-04-01",
  end = Sys.Date(),
  min = "2011-01-01",
  max = Sys.Date(),
  startview = "year"
)


# Selection input of nominal code
selectInput(
  inputId = "nominalid",
  label = "Select the Nominal Code",
  choices = c("", levels(dataset_donations$nominal)),
  multiple = FALSE
)

# Selection input of source group code
selectInput(
  inputId = "sourcegroupid",
  label = "Select the Source Group Code",
  choices = NULL,
  multiple = FALSE
)

# Selection input of source code
selectInput(
  inputId = "sourceid",
  label = "Select the Source Code",
  choices = NULL,
  multiple = FALSE
)

radioButtons(
  inputId = "levelsid",
  label = "Select the Level of Detail of the Graph",
  choices = c("By Nominal" = "nominal", "By Source Group" = "source.group", "By Source Code" = "source")
)

## Boton to create plot
actionButton(inputId = "actionid1",
             label = "Clic to Initiate Graph")

## Code for making the source.group and source input depend on the nominal code
observeEvent(input$nominalid, {
  filtered_donations1 <- dataset_donations %>%
    filter(nominal == input$nominalid) %>%
    distinct(source.group)
  
  updateSelectInput(session, "sourcegroupid", choices = c(filtered_donations1))
  
})

observeEvent(input$sourcegroupid, {
  filtered_donations2 <- dataset_donations %>%
    filter(source.group == input$sourcegroupid) %>%
    distinct(source)
  
  updateSelectInput(session, "sourceid", choices = c(filtered_donations2))
  
})

dataset_donations_base <-  dataset_donations %>%
  select(
    donor.no,
    journal.no,
    donation.date,
    nominal,
    source.group,
    source,
    donation.day,
    donation.week,
    donation.month,
    donation.year,
    donation.amount,
    payment.type
  ) %>%
  mutate(year.unite = strftime(.$donation.date, format = "%Y")) %>%
  mutate(month.unite = strftime(.$donation.date, format = "%m")) %>%
  unite(MY, month.unite, year.unite) 


## Create reactive objects that will depend on date, nominal, source.group and source code


reactive_viz_perc_digi <- reactive({
 dataset_donations_base %>% 
    filter(
      donation.date >= input$dateid1[1] &
      donation.date <= input$dateid1[2]) %>% 
    group_by(MY) %>% 
    mutate(total.donations = sum(donation.amount)) %>% 
    ungroup() %>% 
  mutate(digi.or.phys = case_when(payment.type %in% c(1,2,3,4,5,10,11,12,13,16,18,20) ~ "Phys",
                                  payment.type %in% c(14,15,17,19) ~ "Digi")) %>%
  group_by(MY, digi.or.phys) %>%
  mutate(sum.digital = sum(.$digi.or.phys == "Digi"),
         sum.physical = sum(.$digi.or.phys == "Phys"),
         perc.digi = sum.digital / sum.physical) %>%
  ungroup() %>% 
  distinct(MY, .keep_all = TRUE) %>% 
  select(donation.date, MY, total.donations, perc.digi)

})


reactive_viz_donations <- reactive({
  
  dataset_donations_base %>% 
  group_by_at(vars(MY, input$levelsid)) %>% 
  mutate(
    sum.donations = sum(donation.amount),
    average.donations = mean(donation.amount, na.rm = TRUE),
    number.donations = n()
  ) %>%
  ungroup() %>% 
  distinct(MY, source, .keep_all = TRUE) # In shiny gere goes input$Nominal, source...

})
  

reactive_viz_newdonors <- reactive({
  
  dataset_donations_base %>%
  group_by_at(vars(input$levelsid, donor.no)) %>% # In shiny gere goes input$Nominal, source...
  mutate(donations.per.donor = n()) %>%
  ungroup() %>%
  filter(donations.per.donor == 1) %>%
  group_by_at(vars(MY, input$levelsid)) %>% 
  mutate(sum.new.donors = n()) %>%
  ungroup() %>% 
  select(MY, sum.new.donors, nominal, source.group, source) %>% 
  distinct(MY, source, .keep_all = TRUE)

})


reactive_viz_totaldonors <- reactive({
  dataset_donations_base %>%
  # group_by(donor.no) %>%
  # ungroup() %>%
  group_by_at(vars(MY, input$levelsid)) %>% # In shiny gere goes input$Nominal, source...
  distinct(donor.no, .keep_all = TRUE) %>%
  mutate(donors.per.month = n()) %>%
  ungroup() %>% 
  select(MY, donors.per.month, nominal, source.group, source) %>% 
  distinct(MY, source, .keep_all = TRUE) 

})



reactive_viz_general <- reactive({
  reactive_viz_donations() %>% 
  left_join(reactive_viz_newdonors(), by = c("MY", "nominal", "source.group", "source")) %>% 
  left_join(reactive_viz_totaldonors(), by = c("MY", "nominal", "source.group", "source")) %>%
  select(nominal,
         source.group,
         source, 
         donation.month, 
         donation.year,
         donation.date, 
         MY,
         sum.donations,
         average.donations,
         number.donations,
         sum.new.donors,
         donors.per.month) %>%
  gather(index, value, -c(nominal:MY)) %>%
  mutate_if(is.character, funs(as.factor)) %>%
    select(Donation.Date = donation.date, Value = value, Donation.Year = donation.year, Donation.Month = donation.month, everything())
  
})


  reactiveDonationsFiltered<- reactive({
  if (input$levelsid == "nominal") {
  reactive_viz_general() %>%
      # distinct(MY, nominal, .keep_all = TRUE) %>%
      filter(
      Donation.Date >= input$dateid1[1] &
      Donation.Date <= input$dateid1[2],
      nominal == input$nominalid,
      index == input$graphid
      )


  } else if (input$levelsid == "source.group") {
   reactive_viz_general() %>%
    # distinct(MY, source.group, .keep_all = TRUE) %>%
      filter(
      Donation.Date >= input$dateid1[1] &
      Donation.Date <= input$dateid1[2],
      nominal == input$nominalid,
      source.group == input$sourcegroupid,
      index == input$graphid
      )


  } else if (input$levelsid == "source") {
 reactive_viz_general() %>%
      filter(
      Donation.Date >= input$dateid1[1] &
      Donation.Date <= input$dateid1[2],
      nominal == input$nominalid,
      source.group == input$sourcegroupid,
      source == input$sourceid,
      index == input$graphid
      )
  }
  
})


```


column {.tabset data-width=700}
----------------------

### By Code

```{r}

renderPlotly({
  req(input$actionid1)
  ggplotly((reactiveDonationsFiltered()) %>%
  ggplot(
  aes(Donation.Month,
  Value,
  group = Donation.Year,
  fill = Donation.Year)
  ) +
  geom_col(position = "dodge") +
    theme_economist_white() +
  scale_fill_economist() + 
  labs(x = "Date", 
       y = "Value",
       fill = "") +
  theme(legend.position = "right", text = element_text(family = "Tahoma"), plot.background = element_rect(fill = "white"), plot.margin=unit(c(1,3,2,2.5),"cm"))
  )
})

```


Column {data-width=300 .sidebar}


### General

```{r}

renderPlotly({
  req(input$actionid1)
  ggplotly((reactive_viz_perc_digi()) %>%
  ggplot(
  aes(donation.date, total.donations, label = perc.digi)) +
  geom_line(colour = "darkorange1", alpha = 0.8)  +
  geom_smooth(method = "lm", se = FALSE, colour = "grey40") + 
  theme_economist_white() +
  scale_fill_economist() + 
  labs(x = "Date", 
       y = "Value") +
  theme(legend.position = "right", text = element_text(family = "Tahoma"), plot.background = element_rect(fill = "white"), plot.margin=unit(c(1,3,2,2.5),"cm"))
)
})


```


GeoData {data-width=700}
====================

### Postcodes of Donations and IPU Patients

```{r}
pal <- colorFactor(
  palette = c('red', 'blue', 'green'),
  domain = dataset_donations_postcode_ipu$owner.of.postcode)


leaflet(dataset_donations_postcode_ipu) %>%
  addTiles() %>%  
  setView(-1.581517, 54.77952, zoom = 9) %>%
  addCircles(
    lng = dataset_donations_postcode_ipu$longitude,
    lat = dataset_donations_postcode_ipu$latitude, 
    label = dataset_donations_postcode_ipu$owner.of.postcode,
    color = ~ pal(owner.of.postcode))


```


